spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Incolla qui i tuoi dati estratti dall'URL di Render:

spring.datasource.url=jdbc:postgresql://todo_db_jokx_user:zMQQGQIp6LP8U43BeqWpjoETpOidvhaH@dpg-dacj8tafngtc73dmucb0-a/todo_db_jokx
spring.datasource.username=todo_db_jokx_user
spring.datasource.password=zMQQGQIp6LP8U43BeqWpjoETpOidvhaH