spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://dpg-cacj8tafngtc73dmucb0-a:5432/todo_db_jokx
spring.datasource.username=todo_db_jokx_user
spring.datasource.password=zMQQGQIp6LP8U43BeqWpjoETpOidvhaH