# Connessione al Database su Render
spring.datasource.url=jdbc:postgresql://dpg-dacj8tafngtc73dmucb0-a.frankfurt-postgres.render.com:5432/todo_db_jokx?sslmode=require
spring.datasource.username=todo_db_jokx_user
spring.datasource.password=zMQQGQIp6LP8U43BeqWpjoETpOidvhaH

# Configurazioni Hibernate/JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.initialization-fail-timeout=-1
spring.jpa.defer-datasource-initialization=true